### PR TITLE
Added Offline payment

### PR DESCRIPTION
**Pull request by vIG4Ever**
now if the sender was offline player can pay bills and the money will be updated directly to the database

### CODE REVIEW

**Comment by ElPumpo** [comment]
Reviewed the code and it simply doesn't follow esx standards

**Comment by ElPumpo** [comment]
There's many code details youll find in the esx projects that you dont follow

**Comment by vIG4Ever** [comment]
@ElPumpo i don't know what is the ``esx standards`` but i simply copy paste your code and replaced addmoney with sql bank update

**Comment by ElPumpo** [comment]
If you cant make adjust to other peoples standards dont expect your prs to get merged

**Pull request closed without merging**
